# base.yaml
application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "postmaster@sandboxca40402592b34879ac42a56dcbcbdf52.mailgun.org"
  username: "api"
  password: ""
  timeout_milliseconds: 10000