application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  base_url: "https://api.mailgun.net/v3/sandboxca40402592b34879ac42a56dcbcbdf52.mailgun.org/messages"
  sender_email: "postmaster@sandboxca40402592b34879ac42a56dcbcbdf52.mailgun.org"